#+TITLE: The KOALA experiment for (anti)proton-proton elastic scattering

#+TOC: Table of Content

* Introduction
   TODO:
   - reduce reliance on PANDA and LumiDet
   - paper aims to be a stand-alone paper with limited relation to PANDA
   - p-p as a first step at COSY
   - Full setup with LumiDet at HESR
   - The aim of the paper is to be cited later by the Physics paper

   Content list:
   - Summary of (anti)proton-proton elastic scattering research background
   - Short description of PANDA experiment 
     and its requirements on the precision of luminosity measurements.
   - Description of the method of luminosity measurement used in PANDA and the limitation. 
   - More precise differential cross-section data of antiproton-proton elastic scattering covering a large four-momentum transfer range is needed in PANDA energy regime. 
   - A separate experiment called KOALA is proposed to fulfill this specific need.

* Principle of measurement and experiment setup
   TODO:
   - add summary and citation about Target
   - ask Alfons for reference paper about the Target
   
   Principle of measurement:
   - Description of the strategy that KOALA uses to complement LMD.
   - Key parameter requirements in the design

   Overview of the experiment setup.
   - Dedicated experiment site 
   - The role of cluster target and its property summary
   - Recoil arm for large range of four momentum transfer range
   - Forward arm for background suppression based on TOF (the idea of coincidence measurement)

* Detector systems
   TODO:
   - or put the target here
   
** Recoil detector
   - Sensor design
     - Mechanical and other considerations
   - The electronics (FEE)
   - Performance from lab test ??

** Forward detector
   - Sensor design
     - Packaging
   - The electronics (FEE)

* Data acquisition system
   
  The data acquisition system of KOALA is a VME-based system.
  Off-the-shelf modules from Mesytec are used for the digitization of the amplitude, charge and time information.
  For the recoil detector, the amplitude signal after charge-integration amplifier and shaper is digitized by a peak-sensing ADC (MADC32).
  For the forward detector, the pulse from PMT is directly fed into a QDC (QDC32) for charge measurement.
  The timing information from both the recoil and forward detector are recorded by the same TDC (MTDC32) using conventional Start-Stop method.
  A multi-channel scalor (SIS3820) is also integrated to measure key count rates: 1) count rates of all the four branches of the forward detector for beam position monitoring;
  2) count rates of the overlapping strips of the recoil detector for asymmetry correction; 3) count rates of the DAQ trigger for DAQ efficiency correction.
  All the modules above have 32 measurement channels on board and can hosted in one VME crate.
  The VME controller is SIS3100 from SIS.

  The acceptance of the forward detector only covers a small part of the recoil detector sensors.
  To record the elastic scattering events from the whole range of the recoil angle covered by the recoil detector, KOALA adopts a self-triggering scheme of data acquisition.
  Each sensor of the recoil detector and each arm of the forward detector works independently and generates their own trigger. 
  The trigger from the recoil detector sensor is a coincidence signal between the front-side strip and the rear-side plane, 
  and the trigger from the forward detector arm is a coincidence signal between the two scintillators in the same arm.
  In this way, the rate of the false hit generated by electronic noises can be minimized.
  The final trigger to DAQ system is a common OR of the sub-detectors, as shown in Fig. 1.
  Both elastic and in-elastic scattering events are recorded, and the coincidence between the recoil sensor and the forward detector is carried out in offlline analysis.
  
* * Software framework for simulation, calibration and analysis
   Key points:
    - Overview
      * FairROOT based
      * Simulation, calibration and analysis combined in one framework
    - Simple explanation of task-based design
    - Design of some key components 
      - Unpack
        - Interface to raw data from DAQ : transform raw binary data to KoalaSoft recognizable format
        - Same task flow regardless of the origin of data source
        - Combing online and offline analysis together with FairMQ
      - Digitization : Key component to get meaningful guide from simulation. (Under development)
 
* Calibration and energy reconstruction
   - Method of energy calibration and the procedures
   - Energy reconstruction : Clustering
   - Accuracy of energy measurement: by comparison with calculated value

* Results from beam test
   - DAQ benchmarks : DAQ efficiency
   - The energy spectrum of recoil detector after reconstruction
     - Comparison of the simulation spectrum and real spectrum (To be verified)
   - Recoil and forward correlation and its application for background suppression

* Conclusion and outlook
